version: '3'
services:
  postgres:
    image: postgres:9.5
  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres@postgres/quiz_development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/quiz
    ports:
      - "3000:3000"
    depends_on:
      - postgres
