# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0bce20fb0cdcc11bf8a621b7bd9cdd04dccd0b344b459b16e8c2bdfb8b0dfdc0ddb6a32da07dabd0646c93cfbef7b3ecef18966e51bc8711886f42b351f1b2e

test:
  secret_key_base: 90366b91f8636a6bd7960a0796023ee975c28af89bf9e1c5f942816bc4e648eb0708eb20c670476488eefbcb8825090edaf6f08106a0b8e0b8c5be5995f02bdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
